ci:test

diff --git a/.github/workflows/mirrorchyan_uploading.yml b/.github/workflows/mirrorchyan_uploading.yml
--- a/.github/workflows/mirrorchyan_uploading.yml
+++ b/.github/workflows/mirrorchyan_uploading.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   mirrorchyan_7z:
-    runs-on: macos-latest
+    runs-on: windows-latest
     steps:
       - name: 📥 Download release
         uses: robinraju/release-downloader@v1.8
@@ -15,11 +15,19 @@ jobs:
           latest: true
           fileName: "*"
 
-      - name: Extract 7z
+      - name: 📥 Download kachina-builder release
+        uses: robinraju/release-downloader@v1.8
+        with:
+          repository: "YuehaiTeam/kachina-installer"
+          latest: true
+          fileName: "kachina-builder.exe"
+
+      - name: Extract 7z and create zip
         shell: bash
         run: |
           7z x BetterGI_v*.7z -oun7z
           mv ./BetterGI.Metadata.json ./un7z/BetterGI/.metadata.json
+          7z a -tzip BetterGI.zip un7z/BetterGI -mx=5 -mf=BCJ2 -r -y
 
       - name: Determine version number
         id: get-version
@@ -37,26 +45,40 @@ jobs:
         uses: MirrorChyan/uploading-action@v1
         with:
           filetype: local
-          mirrorchyan_rid: BGI
-          working-directory: ./un7z/
-          pick_files: '["BetterGI"]'
+          mirrorchyan_rid: demo1
+          filename: "BetterGI.zip"
           version_name: ${{ steps.get-version.outputs.version }}
           upload_token: ${{ secrets.MirrorChyanUploadToken }}
           os: win
           arch: x64
 
-  mirrorchyan_exe:
-    runs-on: macos-latest
-    steps:
-      - uses: MirrorChyan/uploading-action@v1
+      - name: Embed Dotnet and VCRedist
+        shell: bash
+        run: |
+          # dotnet
+          VERSION_URL="https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0/latest.version"
+          VERSION=$(curl -fsSL "$VERSION_URL" | tr -d '\r\n')
+          if [ -z "$VERSION" ]; then
+              echo "Cannot get the latest version from $VERSION_URL"
+              exit 1
+          fi
+          INSTALLER_URL="https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/${VERSION}/windowsdesktop-runtime-${VERSION}-win-x64.exe"
+          OUTPUT="windowsdesktop-runtime-${VERSION}-win-x64.exe"
+          echo "Downloading Windows Desktop Runtime version $VERSION from $INSTALLER_URL"
+          curl -fSL -o "$OUTPUT" "$INSTALLER_URL"
+          # vcredist
+          echo "Downloading VCRedist"
+          curl -fSL -o "vc_redist.x64.exe" "https://aka.ms/vs/17/release/vc_redist.x64.exe"
+          # embed
+          echo "Embedding runtimes"
+          ./kachina-builder.exe append -o ./BetterGI.Install.*.exe -f "$OUTPUT" -n "Microsoft.DotNet.DesktopRuntime.8" -f "vc_redist.x64.exe" -n "Microsoft.VCRedist.2015+.x64"
+
+      - name: Upload EXE
+        if: always()
+        uses: MirrorChyan/uploading-action@v1
         with:
-          filetype: latest-release
+          filetype: local
+          mirrorchyan_rid: demo1
           filename: "BetterGI.Install.*.exe"
-          extra_zip: true
-          mirrorchyan_rid: BGI
-
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          owner: babalae
-          repo: better-genshin-impact
+          version_name: ${{ steps.get-version.outputs.version }}
           upload_token: ${{ secrets.MirrorChyanUploadToken }}
-
